plugins {
    id 'net.fabricmc.fabric-loom' version '1.16-SNAPSHOT'
    id 'com.modrinth.minotaur' version '2.+'
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "perfectlypacked" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

repositories {
    maven {
        name = 'Quilt'
        url = 'https://maven.quiltmc.org/repository/release'
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    def projectName = project.name
    inputs.property "projectName", projectName

    from("LICENSE") {
        rename { "${it}_$projectName"}
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "perfectly-packed"
    gameVersions = ["26.1", "26.1.1", "26.1.2"]
    versionType = "alpha"
    uploadFile = jar
    changelog = """- Ported to 26.1
        - Added a configuration through [YACL](https://modrinth.com/mod/yacl), along with a GUI if [Mod Menu](https://modrinth.com/mod/modmenu) is installed.
        TODO:
        - Update packings of 28, 29, 39, 41, 50, 51, 53 and 55 squares to their improved versions
        - Add packings for sizes up to 99 to support larger max stack sizes""".stripIndent()
    dependencies {
        required.project "yacl"
        optional.project "modmenu"
    }
}
